# Generated by mc: 9:49 4.20.2019.
#
	.data
	.text
main:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -36		# allocate locals
	li	$v0, 0
	sw	$v0, -32($fp)
	li	$v0, 0
	sw	$v0, -12($fp)
	li	$v0, 4
	sw	$v0, -12($fp)
	li	$v0, 2
	sw	$v0, -16($fp)
	li	$v0, 8
	sw	$v0, -20($fp)
	lw	$t1, -12($fp)
	lw	$t2, -20($fp)
	mul	$v0, $t1, $t2
	sw	$v0, -24($fp)
	lw	$t1, -16($fp)
	lw	$t2, -24($fp)
	add	$v0, $t1, $t2
	sw	$v0, -28($fp)
	lw	$v0, -28($fp)
	sw	$v0, -32($fp)
	lw	$v0, -32($fp)
	sw	$v0, -36($fp)
	lw	$a0, -36($fp)
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	li	$v0, 17			# $v0 gets exit code for syscall
	syscall				# Exit here
