# Generated by mc: 9:49 4.20.2019.
#
	.data
	.text
main:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -24		# allocate locals
	li	$v0, 0
	sw	$v0, -20($fp)
	li	$v0, 14039
	sw	$v0, -8($fp)
	li	$v0, 1529
	sw	$v0, -12($fp)
	lw	$t1, -8($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, -12($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	gcd
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 8		# deallocate args
	sw	$v0, -16($fp)
	lw	$v0, -16($fp)
	sw	$v0, -20($fp)
	lw	$v0, -20($fp)
	sw	$v0, -24($fp)
	lw	$a0, -24($fp)
	li	$v0, 1			# $v0 gets print_int code for syscall
	syscall				# print
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	li	$v0, 17			# $v0 gets exit code for syscall
	syscall				# Exit here
mod:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -24		# allocate locals
	li	$v0, 0
	sw	$v0, -4($fp)
	lw	$t1, 8($fp)
	lw	$t2, -4($fp)
	slt	$v0, $t1, $t2
	sw	$v0, -8($fp)
	lw	$v0, -8($fp)
	beqz	$v0, l0
	li	$v0, 0
	sw	$v0, -12($fp)
	lw	$v0, -12($fp)
	j	l1
l0:	nop
l2:	nop
	lw	$t1, 12($fp)
	lw	$t2, 8($fp)
	sub	$v0, $t2, $t1		# >=
	slti	$v0, $v0, 1
	sw	$v0, -16($fp)
	lw	$v0, -16($fp)
	beqz	$v0, l3
	lw	$t1, 12($fp)
	lw	$t2, 8($fp)
	sub	$v0, $t1, $t2
	sw	$v0, -20($fp)
	lw	$v0, -20($fp)
	sw	$v0, 12($fp)
	j	l2
l3:	nop
l1:	nop
	lw	$v0, 12($fp)
	sw	$v0, -24($fp)
	lw	$v0, -24($fp)
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	jr	$ra				# return
abs:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -24		# allocate locals
	li	$v0, 0
	sw	$v0, -4($fp)
	lw	$t1, 8($fp)
	lw	$t2, -4($fp)
	slt	$v0, $t1, $t2
	sw	$v0, -8($fp)
	lw	$v0, -8($fp)
	beqz	$v0, l4
	li	$v0, 0
	sw	$v0, -12($fp)
	lw	$t1, -12($fp)
	lw	$t2, 8($fp)
	sub	$v0, $t1, $t2
	sw	$v0, -16($fp)
	lw	$v0, -16($fp)
	sw	$v0, -20($fp)
	lw	$v0, -20($fp)
	j	l5
l4:	nop
	lw	$v0, 8($fp)
	sw	$v0, -24($fp)
	lw	$v0, -24($fp)
l5:	nop
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	jr	$ra				# return
gcd:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -68		# allocate locals
	lw	$t1, 12($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	abs
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 4		# deallocate args
	sw	$v0, -4($fp)
	lw	$v0, -4($fp)
	sw	$v0, 12($fp)
	lw	$t1, 8($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	abs
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 4		# deallocate args
	sw	$v0, -8($fp)
	lw	$v0, -8($fp)
	sw	$v0, 8($fp)
	li	$v0, 0
	sw	$v0, -12($fp)
	lw	$t1, 12($fp)
	lw	$t2, -12($fp)
	li	$v0, 0
	sub	$t1, $t1, $t2		# ==
	li	$t2, 1
	movz	$v0, $t2, $t1
	sw	$v0, -16($fp)
	lw	$v0, -16($fp)
	beqz	$v0, l6
	lw	$v0, -16($fp)
	sw	$v0, -32($fp)
	j	l7
l6:	nop
	li	$v0, 0
	sw	$v0, -24($fp)
	lw	$t1, 8($fp)
	lw	$t2, -24($fp)
	li	$v0, 0
	sub	$t1, $t1, $t2		# ==
	li	$t2, 1
	movz	$v0, $t2, $t1
	sw	$v0, -28($fp)
	lw	$v0, -28($fp)
	sw	$v0, -32($fp)
l7:	nop
	lw	$v0, -32($fp)
	beqz	$v0, l8
	lw	$t1, 12($fp)
	lw	$t2, 8($fp)
	add	$v0, $t1, $t2
	sw	$v0, -36($fp)
	lw	$v0, -36($fp)
	sw	$v0, -40($fp)
	lw	$v0, -40($fp)
	j	l9
l8:	nop
	lw	$t1, 8($fp)
	lw	$t2, 12($fp)
	slt	$v0, $t2, $t1		# >
	sw	$v0, -44($fp)
	lw	$v0, -44($fp)
	beqz	$v0, l10
	lw	$t1, 8($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, 12($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	mod
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 8		# deallocate args
	sw	$v0, -48($fp)
	lw	$t1, 12($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, -48($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	gcd
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 8		# deallocate args
	sw	$v0, -52($fp)
	lw	$v0, -52($fp)
	sw	$v0, -56($fp)
	lw	$v0, -56($fp)
	j	l11
l10:	nop
	lw	$t1, 12($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, 8($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	mod
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 8		# deallocate args
	sw	$v0, -60($fp)
	lw	$t1, -60($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, 8($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	gcd
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 8		# deallocate args
	sw	$v0, -64($fp)
	lw	$v0, -64($fp)
	sw	$v0, -68($fp)
	lw	$v0, -68($fp)
l11:	nop
l9:	nop
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	jr	$ra				# return
